[
    {
        "id": "0",
        "name": "Ringz Aug",
        "mbanner": "/m",
        "sbanner": "/srs",
        "latest": "/m",
        "category": "/c",
        "allData": "/m",
        "webseries": "/srs",
        "hubLinkLoader": "https://streamhub.to/d/#/ddl",
        "tapLinkLoader": "https://streamtape.to",
        "notification": "Some Movies & Series are not working. We are uploading soon....\r\nBoth Server are Working Fine.....\r\n\r\nIf any issue report the issue in Our Telegram Channel.\r\n\r\n.",
        "version": "5.0.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzstudio.pages.dev/",
        "link1": "cdn.jsdelivr.net/gh/zsaergddtgdgt/aswaqrdfdserdfg@a0d48d16b0d8c67c0c728d107b41e1d11ebedbb8",
        "link2": "cdn.jsdelivr.net/gh/zsaergddtgdgt/aswaqrdfdserdfg@a0d48d16b0d8c67c0c728d107b41e1d11ebedbb8",
        "tab": "52",
        "openNoti": "Enter the below code :\r\n\r\nIf you are using any Adblocker/DNS then disable it first.\r\nANY Issue Join Telegram : https://t.me/ringzstudio\r\n.",
        "pass": "5689",
        "otherAppLink": "https://bit.ly/desihubApp",
        "otherAppText": "🔥🔥 18+ Adult Movies Click Here",
        "Akey": "[ \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\" ]",
        "AUrl": "https://streamhub.to/api/file/direct_link?key=#1&file_code=#2&hls=1",
        "useKey": "TRUE",
        "useKey480pServer1": "",
        "categoryAds": "FALSE",
        "hindiNoti": "",
        "engNoti": "",
        "server3UrlsStart": "",
        "server3Urls": "",
        "server3Flag": "",
        "server3WebvwFlag": "",
        "server4Url": "",
        "server4UrlStart": "",
        "server4Flag": "",
        "webServer3Flag": "",
        "websrsserver3WebvwFlag": "",
        "webServer4Flag": "",
        "server1Flag": "",
        "server1UrlStart": "",
        "s3getData": "",
        "s3getData1": "",
        "s3getData2": "",
        "s3getData3": "",
        "s3getError": "",
        "s3getError1": "",
        "s3getError2": "",
        "s3getError3": "",
        "s4getData": "",
        "s4getData1": "",
        "s4getData2": "",
        "s4getData3": "",
        "s4getError": "",
        "s4getError1": "",
        "s4getError2": "",
        "s4getError3": "",
        "720pError": "",
        "480Error": "",
        "server2FlagMvs": "",
        "server2FlagSrs": "",
        "telgramUrl": "",
        "useSecKey": "",
        "secKey": "",
        "480pS1Flag": "",
        "480pS2Flag": "",
        "480pS3Flag": "",
        "480pS4Flag": "",
        "apkUrl": ""
    },
    {
        "id": "1",
        "name": "Ringz Aug update",
        "mbanner": "/test.json",
        "sbanner": "/srs.json",
        "latest": "/test.json",
        "category": "/c.json",
        "allData": "/test.json",
        "webseries": "/srs.json",
        "hubLinkLoader": "https://streamhub.to/d/#/ddl",
        "tapLinkLoader": "https://streamtape.to",
        "notification": "Some Movies & Series are not working. We are uploading soon....\r\nBoth Server are Working Fine.....\r\n\r\nIf any issue report the issue in Our Telegram Channel.\r\n\r\n.",
        "version": "5.0.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzstudio.pages.dev/",
        "link1": "cdn.jsdelivr.net/gh/zsaergddtgdgt/hsdhsggvgssgsf@54ae3631a19a5f040e3016ca6cc370600b4ea543",
        "link2": "cdn.jsdelivr.net/gh/zsaergddtgdgt/hsdhsggvgssgsf@54ae3631a19a5f040e3016ca6cc370600b4ea543",
        "tab": "52",
        "openNoti": "Enter the below code :\r\n\r\nIf you are using any Adblocker/DNS then disable it first.\r\nANY Issue Join Telegram : https://t.me/ringzstudio\r\n.",
        "pass": "5689",
        "otherAppLink": "https://bit.ly/desihubApp",
        "otherAppText": "🔥🔥 18+ Adult Movies Click Here",
        "Akey": "[ \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\" ]",
        "AUrl": "https://streamhub.to/api/file/direct_link?key=#1&file_code=#2&hls=1",
        "useKey": "TRUE",
        "useKey480pServer1": "",
        "categoryAds": "FALSE\n",
        "hindiNoti": "",
        "engNoti": "",
        "server3UrlsStart": "",
        "server3Urls": "",
        "server3Flag": "",
        "server3WebvwFlag": "",
        "server4Url": "",
        "server4UrlStart": "",
        "server4Flag": "",
        "webServer3Flag": "",
        "websrsserver3WebvwFlag": "",
        "webServer4Flag": "",
        "server1Flag": "",
        "server1UrlStart": "",
        "s3getData": "",
        "s3getData1": "",
        "s3getData2": "",
        "s3getData3": "",
        "s3getError": "",
        "s3getError1": "",
        "s3getError2": "",
        "s3getError3": "",
        "s4getData": "",
        "s4getData1": "",
        "s4getData2": "",
        "s4getData3": "",
        "s4getError": "",
        "s4getError1": "",
        "s4getError2": "",
        "s4getError3": "",
        "720pError": "",
        "480Error": "",
        "server2FlagMvs": "",
        "server2FlagSrs": "",
        "telgramUrl": "",
        "useSecKey": "",
        "secKey": "",
        "480pS1Flag": "",
        "480pS2Flag": "",
        "480pS3Flag": "",
        "480pS4Flag": "",
        "apkUrl": ""
    },
    {
        "id": "2",
        "name": "Ringz Aug update",
        "mbanner": "/test.json",
        "sbanner": "/srs.json",
        "latest": "/test.json",
        "category": "/c.json",
        "allData": "/test.json",
        "webseries": "/srs.json",
        "hubLinkLoader": "https://streamhub.to/d/#/ddl",
        "tapLinkLoader": "https://streamtape",
        "notification": " !!! Important Update!!!!!!\r\nFor Some Users Server 1 is not working, you can use server 2 until we fix.. or use can use connect VPN & use server 1.\r\n.\r\nKuch users ka server 1 nhi chal rha h vo server 2 use kre.\r\n.\r\n.\r\n.\r\n\r\nIf any issue report the issue in Our Telegram Channel.\r\n\r\n.",
        "version": "5.0.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzstudio.pages.dev/",
        "link1": "hsdhsgg.pages.dev",
        "link2": "hsdhsgg.pages.dev",
        "tab": "52",
        "openNoti": "Enter the below code :\r\n\r\nIf you are using any Adblocker/DNS then disable it first.\r\nANY Issue Join Telegram : https://t.me/ringzstudio\r\n.",
        "pass": "5689",
        "otherAppLink": "https://bit.ly/desihubApp",
        "otherAppText": "FALSE",
        "Akey": "[ \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\" ]",
        "AUrl": "https://streamhub.to/api/file/direct_link?key=#1&file_code=#2&hls=1",
        "useKey": "TRUE",
        "useKey480pServer1": "",
        "categoryAds": "TRUE",
        "hindiNoti": "NOTE : अगर मूवी दो भाषा में है तो , प्लेयर स्क्रीन में 3 डॉट्स पर क्लिक करके भाषा बदले , अभी सर्वर 1 ही सपोर्ट करता हैं",
        "engNoti": "NOTE : If Movie is in Dual Audio, then In Player click on 3 dots and change audio, Currently this feature is supported by SERVER 1.",
        "server3UrlsStart": "https://desiupload",
        "server3Urls": "https://desiupload.co/?op=download2&id=#",
        "server3Flag": "TRUE",
        "server3WebvwFlag": "TRUE",
        "server4Url": "https://uptomega.me/?op=download2&id=#&method_free=Free%20Download%20%3E%3E",
        "server4UrlStart": "https://uptomega",
        "server4Flag": "TRUE",
        "webServer3Flag": "TRUE",
        "websrsserver3WebvwFlag": "TRUE",
        "webServer4Flag": "TRUE",
        "server1Flag": "TRUE",
        "server1UrlStart": "https://streamhub",
        "s3getData": "",
        "s3getData1": "",
        "s3getData2": "",
        "s3getData3": "",
        "s3getError": "",
        "s3getError1": "",
        "s3getError2": "",
        "s3getError3": "",
        "s4getData": "",
        "s4getData1": "",
        "s4getData2": "",
        "s4getData3": "",
        "s4getError": "",
        "s4getError1": "",
        "s4getError2": "",
        "s4getError3": "",
        "720pError": "",
        "480Error": "",
        "server2FlagMvs": "",
        "server2FlagSrs": "",
        "telgramUrl": "https://t.me/ringzstudio",
        "useSecKey": "",
        "secKey": "",
        "480pS1Flag": "",
        "480pS2Flag": "",
        "480pS3Flag": "",
        "480pS4Flag": "",
        "apkUrl": ""
    },
    {
        "id": "3",
        "name": "Ringz March update",
        "mbanner": "/test.json",
        "sbanner": "/srs.json",
        "latest": "/test.json",
        "category": "/cn.json",
        "allData": "/test.json",
        "webseries": "/srs.json",
        "hubLinkLoader": "https://streamhub.ink/d/#/ddl",
        "tapLinkLoader": "https://streamtape",
        "notification": ".\n!!!!!!!!!! IMPORTANT UPDATE !!!!!!!!\nIf one server is slow then use another server..\n.\nAgar ek server slow chal rha h to dusra server use kre...\n.\nIf any issue report the issue in Our Telegram Channel.\n.",
        "version": "5.2.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzstudio.pages.dev/",
        "link1": "hsdhsgg.pages.dev",
        "link2": "hsdhsgg.pages.dev",
        "tab": "52",
        "openNoti": "Enter the below code :\n\nIf you are using any Adblocker/DNS then disable it first.\nANY Issue Join Telegram : https://t.me/ringzstudio\n.",
        "pass": "5689",
        "otherAppLink": "https://bit.ly/desihubApp",
        "otherAppText": "FALSE",
        "Akey": "[ \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\n \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\" ]",
        "AUrl": "https://streamhub.ink/api/file/direct_link?key=#1&file_code=#2&hls=1",
        "useKey": "TRUE",
        "useKey480pServer1": "TRUE",
        "categoryAds": "TRUE",
        "hindiNoti": "NOTE : अगर मूवी दो भाषा में है तो , प्लेयर स्क्रीन में 3 डॉट्स पर क्लिक करके भाषा बदले , अभी सर्वर 1,3,4 ही सपोर्ट करता हैं",
        "engNoti": "NOTE : If Movie is in Dual Audio, then In Player click on 3 dots and change audio, Currently this feature is supported by SERVER 1,3,4.\r\nIf Server 1,2 is slow then use server 3 or 4",
        "server3UrlsStart": "[\"desiupload.co\",\"uptomega.net\", \"uploadraja.com\",\"uploadbuzz.cc\" ]",
        "server3Urls": "https://^1/?op=download2&id=#",
        "server3Flag": "TRUE",
        "server3WebvwFlag": "TRUE",
        "server4Url": "https://^1/?op=download2&id=#&method_free=Free%20Download%20%3E%3E",
        "server4UrlStart": "[\"desiupload.co\",\"uptomega.net\", \"uploadraja.com\",\"uploadbuzz.cc\" ]",
        "server4Flag": "TRUE",
        "webServer3Flag": "TRUE",
        "websrsserver3WebvwFlag": "TRUE",
        "webServer4Flag": "TRUE",
        "server1Flag": "TRUE",
        "server1UrlStart": "https://streamhub",
        "s3getData": "document.getElementById(\"direct_link\").innerHTML",
        "s3getData1": "document.getElementsByClassName('btn btn-dow')[0].href",
        "s3getData2": "document.getElementsByClassName('btn btn-primary btn-block mb-4')[0].href",
        "s3getData3": "document.getElementsByClassName('download')[0].href",
        "s3getError": "document.getElementsByClassName('alert alert-danger')[0].innerHTML",
        "s3getError1": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s3getError2": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s3getError3": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getData": "document.getElementById(\"direct_link\").innerHTML",
        "s4getData1": "document.getElementsByClassName('btn btn-dow')[0].href",
        "s4getData2": "document.getElementsByClassName('download')[0].href",
        "s4getData3": "document.getElementsByClassName('download')[0].href",
        "s4getError": "document.getElementsByClassName('alert alert-danger')[0].innerHTML",
        "s4getError1": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError2": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError3": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "720pError": "https://ereviewwala.com/Apps/DesiHub/linkServer",
        "480Error": "https://ereviewwala.com/Apps/DesiHub/linkServer480p",
        "server2FlagMvs": "TRUE",
        "server2FlagSrs": "TRUE",
        "telgramUrl": "https://t.me/ringzstudio",
        "useSecKey": "TRUE",
        "secKey": "FA0518FADC0D80DB05E4470F6E011BEF825AFBBA",
        "480pS1Flag": "TRUE",
        "480pS2Flag": "TRUE",
        "480pS3Flag": "TRUE",
        "480pS4Flag": "TRUE",
        "apkUrl": ""
    },
    {
        "id": "4",
        "name": "Ringz Oct update",
        "mbanner": "/test.json",
        "sbanner": "/srs.json",
        "latest": "/test.json",
        "category": "/cn.json",
        "allData": "/test.json",
        "webseries": "/srs.json",
        "hubLinkLoader": "https://streamhub.ink/d/#/ddl",
        "tapLinkLoader": "https://streamtape",
        "notification": "!!!!!!!!!! IMPORTANT UPDATE !!!!!!!!\r\n\r\nSome users with Android version 13 are experiencing issues with downloading. We will fix it soon.\r\n.\r\nकुछ यूज़र्स जो Android 13 का उपयोग कर रहे हैं, उन्हें डाउनलोड करने में समस्या हो रही है। हम जल्दी इसे ठीक करेंगे।\r\n.\r\nIf App opened via Notification then sometime movie not playing..So close the app & open again..\r\n.\r\nयदि ऐप नोटिफिकेशन के माध्यम से खुलता है तो कभी-कभी मूवी नहीं चलती है.. इसलिए ऐप को बंद करें और दोबारा खोलें।\r\n.\r\nJoin Telegram Channel for update.. If face any issue you can report on telegram also\r\n.",
        "version": "5.3.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzstudio.pages.dev/",
        "link1": "hsdhsgg.pages.dev",
        "link2": "hsdhsgg.pages.dev",
        "tab": "52",
        "openNoti": "Enter the below code :\r\n\r\nIf you are using any Adblocker/DNS then disable it first.\r\nANY Issue Join Telegram : https://t.me/ringzstudio\r\n.",
        "pass": "5689",
        "otherAppLink": "https://bit.ly/46UiVSD",
        "otherAppText": "🔥 🔥 18+ DesiHub App Click Here 🔥 🔥",
        "Akey": "[ \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\",\r\n \"718wdpllqsxv2jnnke0\", \"716jt2l3supa4vhcrsy\", \"714srjee5l8n93ncrpk\", \"712o2r4vs69l5tfkgd5\", \"711lrqghli08p43kr9s\", \"709joqnbj6i0ucjaf7e\", \"692e3brlin5482cvrj4\", \"691z0rmj6vojekwwled\", \"659umoy3qmr1fm6la5e\", \"602enp18f9vc540ylds\", \"400svpfdiiyyh4mulfv\" ]",
        "AUrl": "https://streamhub.ink/api/file/direct_link?key=#1&file_code=#2&hls=1",
        "useKey": "TRUE",
        "useKey480pServer1": "TRUE",
        "categoryAds": "TRUE",
        "hindiNoti": "ध्यान दें : यदि सर्वर फिल्में चलाने में बहुत अधिक समय ले रहा है तो ऐप को पुनरारंभ करें और पुनः प्रयास करें।\r\n\r\nयदि किसी भी समस्या का सामना करना पड़ रहा है तो हमारे टेलीग्राम चैनल पर रिपोर्ट करें",
        "engNoti": "Note : If server taking too much time to play movies/series then restart the app & try again.\r\n\r\nIf facing any issue then report us on Telegram channel",
        "server3UrlsStart": "[\"desiupload.co\",\"uptomega.net\", \"uploadraja.com\",\"uploadbuzz.cc\" ]",
        "server3Urls": "https://^1/?op=download2&id=#",
        "server3Flag": "TRUE",
        "server3WebvwFlag": "TRUE",
        "server4Url": "https://^1/?op=download2&id=#&method_free=Free%20Download%20%3E%3E",
        "server4UrlStart": "[\"desiupload.co\",\"uptomega.net\", \"uploadraja.com\",\"uploadbuzz.cc\" ]",
        "server4Flag": "TRUE",
        "webServer3Flag": "TRUE",
        "websrsserver3WebvwFlag": "TRUE",
        "webServer4Flag": "TRUE",
        "server1Flag": "TRUE",
        "server1UrlStart": "https://streamhub",
        "s3getData": "document.getElementById(\"direct_link\").innerHTML",
        "s3getData1": "document.getElementsByClassName('btn btn-dow')[0].href",
        "s3getData2": "document.getElementsByClassName('btn btn-primary btn-block mb-4')[0].href",
        "s3getData3": "document.getElementsByClassName('download')[0].href",
        "s3getError": "document.getElementsByClassName('alert alert-danger')[0].innerHTML",
        "s3getError1": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s3getError2": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s3getError3": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getData": "document.getElementById(\"direct_link\").innerHTML",
        "s4getData1": "document.getElementsByClassName('btn btn-dow')[0].href",
        "s4getData2": "document.getElementsByClassName('download')[0].href",
        "s4getData3": "document.getElementsByClassName('download')[0].href",
        "s4getError": "document.getElementsByClassName('alert alert-danger')[0].innerHTML",
        "s4getError1": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError2": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError3": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "720pError": "https://ereviewwala.com/Apps/DesiHub/linkServer",
        "480Error": "https://ereviewwala.com/Apps/DesiHub/linkServer480p",
        "server2FlagMvs": "TRUE",
        "server2FlagSrs": "TRUE",
        "telgramUrl": "https://t.me/ringzstudio",
        "useSecKey": "TRUE",
        "secKey": "FA0518FADC0D80DB05E4470F6E011BEF825AFBBA",
        "480pS1Flag": "TRUE",
        "480pS2Flag": "TRUE",
        "480pS3Flag": "TRUE",
        "480pS4Flag": "TRUE",
        "apkUrl": "https://weathered.softtechstudio1.workers.dev/0:/Ringz/5.3/RingzMaster.apk"
    },
    {
        "id": "5",
        "name": "Ringz Aug 2024 update",
        "mbanner": "/test.json",
        "sbanner": "/srs.json",
        "latest": "/test.json",
        "category": "/cn.json",
        "allData": "/test.json",
        "webseries": "/srs.json",
        "desihub": "/desihub.json",
        "anime": "/anime.json",
        "tapLinkLoader": "https://streamtape",
        "notification": "\r\nJoin Telegram Channel for update..\r\n If face any issue you can report on telegram also\r\n.",
        "version": "5.5.0",
        "closeVersion": "1.0.0",
        "playlink": "https://ringzapk.com/",
        "link1": "ksnvbhsbvujcadgbvui.pages.dev",
        "link2": "ksnvbhsbvujcadgbvui.pages.dev",
        "tab": "52",
        "otherAppLink": "https://bit.ly/46UiVSD",
        "otherAppText": "FALSE",
        "categoryAds": "TRUE",
        "hindiNoti": "ध्यान दें : यदि सर्वर फिल्में चलाने में बहुत अधिक समय ले रहा है तो ऐप को पुनरारंभ करें और पुनः प्रयास करें।\r\n\r\nयदि किसी भी समस्या का सामना करना पड़ रहा है तो हमारे टेलीग्राम चैनल पर रिपोर्ट करें",
        "engNoti": "Note : If server taking too much time to play movies/series then restart the app & try again.\r\n\r\nIf facing any issue then report us on Telegram channel",
        "server1FlagMvs": "TRUE",
        "server2FlagMvs": "TRUE",
        "tapeFlagMvs": "TRUE",
        "server4FlagMvs": "TRUE",
        "server4WebViewFlag": "TRUE",
        "server4Url": "https://^1/?op=download2&id=#&method_free=Free%20Download%20%3E%3E",
        "server4UrlsStart": "[\"desiupload.co\",\"uptomega.net\", \"uploadraja.com\",\"uploadbuzz.cc\" ]",
        "480pS1Flag": "TRUE",
        "480pS2Flag": "TRUE",
        "480pS3Flag": "TRUE",
        "480pS4Flag": "TRUE",
        "server1FlagSrs": "TRUE",
        "server2FlagSrs": "TRUE",
        "server3FlagSrs": "TRUE",
        "server4FlagSrs": "TRUE",
        "server4WebViewFlagSrs": "TRUE",
        "tapGetData": "document.getElementById('mainvideo').src",
        "tapGetDataError": "document.title",
        "s4getData": "document.getElementById(\"direct_link\").innerHTML",
        "s4getData1": "document.getElementsByClassName('btn btn-dow')[0].href",
        "s4getData2": "document.getElementsByClassName('download')[0].href",
        "s4getData3": "document.getElementsByClassName('download')[0].href",
        "s4getError": "document.getElementsByClassName('alert alert-danger')[0].innerHTML",
        "s4getError1": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError2": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "s4getError3": "document.getElementsByName(\"msg_title\")[0].innerHTML",
        "720pError": "https://ereviewwala.com/Apps/DesiHub/linkServer",
        "480Error": "https://ereviewwala.com/Apps/DesiHub/linkServer480p",
        "telgramUrl": "https://t.me/ringzstudio",
        "useSecKey": "TRUE",
        "secKey": "0B02E84AF68CB34A49CFDD58C265910198EC0348CE5DE26C14346A665443ECB0",
        "apkUrl": "https://pub-0ee792871ac04d1f85c9501b277aeed1.r2.dev/RingzMain.apk"
    }
]